config/routes.rb
Rails.application.routes.draw do
  root :to => 'recipes#index'
  resources :users
  resources :categories
  resources :recipes
  resources :sessions
 
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


  get 'users/index'
  get 'users/new'
  get 'users/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user
    before_action :categories

    

    private
    def categories
        @categories = Category.all
    end

    def fetch_user
        @current_user = User.find_by :id => session[:user_id] 
        session[:user_id] = nil unless @current_user.present? 
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_for_admin, :only => [:index]
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @categories = Category.all
  end

  def create
    category = Category.create category_params
    redirect_to category
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    category = Category.find params[:id]
    category.update category_params
    redirect_to category
  end

  def show
    @category = Category.find params[:id]
    @recipes = @category.recipes
  end

  def destroy
    category = Category.find params[:id]
    category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name, :description)
  end

  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # show all recipes
  def index
    @recipes = Recipe.all
  end

  # create new recipes
  def new
    @recipe = Recipe.new
  end

  def create
    recipe = @current_user.recipes.new recipe_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      recipe.image = req["public_id"]
      recipe.save
    end
    
    @current_user.recipes << recipe
    redirect_to recipe
  end

  # edit recipes
  def edit
    @recipe = Recipe.find params[:id]
    @categories = @recipe.categories
  end

  # make updates to recipe
  def update
    recipe = Recipe.find params[:id]
    if params[:file].present? 
      req = Cloudinary::Uploader.upload(params[:file])
      recipe.image = req["public_id"]
      recipe.save
    end
    recipe.update recipe_params
    redirect_to recipe
  end

  # Show individual recipes
  def show
    @recipe = Recipe.find params[:id]
    @categories = @recipe.categories
    @can_edit = @current_user == @recipe.user || current_user.admin?
  end

  # Delete recipes
  def destroy
    recipe = Recipe.find params[:id]
    recipe.destroy
    redirect_to recipes_path
  end

  private
    def recipe_params
      params.require(:recipe).permit(:title, :description, :servings, :preptime, :cooktime, :ingredients, :instructions, :image, :video, category_ids: [])
    end


  end

  

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  # Sign up / create new user / session
  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to recipes_path
    else
      flash[:error] = "Invalid username or password"
      redirect_to login_path
    end
  end

  # Destroy / close session when the user logs out
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :fetch_user

  # show the users profile with all recipes
  def show
    @user = @current_user
    @recipes = Recipe.all
  end

  # new user sign up
  def new
      @user = User.new
  end

  def create
      @user = User.new user_params 
      if @user.save
          session[:user_id] = @user.id
          redirect_to root_path
      else
        render :new
      end
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
# Helpers for better embedding and manipulation of videos
# Place this code in app/helpers/videos_helper.rb
# Then from any view you can add:
#
#    <%= get_video_iframe('http://the.video.url') %>
#
# Optionally you can add width and height.
#
#    <%= get_video_iframe('http://the.video.url', '1600px', '900px') %>
#
# Thanks to https://stackoverflow.com/a/27878890/1498118

module VideosHelper

    require 'net/http'
  
    # Regex to find YouTube's and Vimeo's video ID
    YOUTUBE_REGEX = %r(^(http[s]*:\/\/)?(www.)?(youtube.com|youtu.be)\/(watch\?v=){0,1}([a-zA-Z0-9_-]{11}))
    VIMEO_REGEX = %r(^https?:\/\/(?:.*?)\.?(vimeo)\.com\/(\d+).*$)
  
    # Finds YouTube's video ID from given URL or [nil] if URL is invalid
    # The video ID matches the RegEx \[a-zA-Z0-9_-]{11}\
    def find_youtube_id url 
      url = sanitize url
      matches = YOUTUBE_REGEX.match url.to_str
      if matches
        matches[6] || matches[5]
      end
    end
  
    # Get YouTube video iframe from given URL
    def get_youtube_iframe url, width, height
      youtube_id = find_youtube_id url
  
      result = %(<iframe title="YouTube video player" width="#{width}"
                  height="#{height}" src="//www.youtube.com/embed/#{ youtube_id }"
                  frameborder="0" allowfullscreen></iframe>)
      result.html_safe
    end
  
    # Finds Vimeo's video ID from given URL or [nil] if URL is invalid
    def find_vimeo_id url
      url = sanitize url
      matches = VIMEO_REGEX.match url.to_str
      matches[2] if matches
    end
  
    # Get Vimeo video iframe from given URL
    def get_vimeo_iframe url, width, height
      vimeo_id = find_vimeo_id url
      uri = "https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/#{ vimeo_id }&width=#{ width }&height=#{ height }"
      # see -> https://stackoverflow.com/a/4581095/1498118
      response = Net::HTTP.get( URI.parse( uri ))
      json = JSON.parse response
      json['html'].html_safe
    end
  
    # Main function
    # Return a video iframe
    # If the url provided is not a valid YouTube or Vimeo url it returns [nil]
    def get_video_iframe(url, width = "515px", height = "320px")
      if find_vimeo_id(url)
        get_vimeo_iframe(url, width, height) 
      elsif find_youtube_id(url)
        get_youtube_iframe(url, width, height) 
      end
    end
  end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form_spacing' %><br>

    <%= f.label :description %><br>
    <%= f.text_area :description, size: "100x2", :class => 'input_text form_spacing' %><br>

    <%= f.submit class: 'submit_button' %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<h1>All Categories</h1>
<p>Click on the category to make edits.</p>

<%@categories.each do |category| %>
    <li>
        <%= link_to category.name, category %>
    </li>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<p><%= @category.description %></p>

<% if @current_user.try(:admin?) %>
    <%= link_to "Edit category", edit_category_path(@category), :class => "control_buttons" %>
    <%= link_to "Delete category", @category, :method => :delete, :data => { :confirm => 'Are you sure?'}, :class => "control_buttons" %>
<% end %>


<h2>Recipes</h2>
<div class="recipe_grid">
  <ul class="border">
    <% @recipes.each do |recipe| %>
      <div class="show_image">
        <div class="index_thumbnail">
           <%= link_to image_tag(recipe.image), recipe%>
        </div>
        <div class="index_content">
          <%= link_to recipe.title, recipe_path(recipe), :class => 'recipe_show_name' %>
        </div>
    </div>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eating w Eyes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="/img/favicon.png">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- CLOUNDINARY -->
    <%= cloudinary_js_config %>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Fredoka:wght@700&family=Poppins:wght@400;600&display=swap');
    </style>
  </head>

  <body>
    <div class="top_banner">
      <div class="banner_text">
        <p>Do you have a headache? You're probably dehydrated </p>
      </div>
    </div>

    <div class="header">
      <div class="logo_container">
      <img class="logo_header" src="/img/eatingweyes_logo.png" alt="eating w eyes logo">
    </div>

      <div class="nav_bg">
        <div class="nav_container">
          <nav>
              <%= link_to "Home", recipes_path, :class => 'nav_tab left_border' %>
              <div class="dropdown">
                <button class="dropbtn">Categories&#160; <i class="arrow down"></i></p></button>
                <div class="dropdown-content ">
                <% Category.all.each do |category| %>
                    <a href="<%= category_path(category) %>"><%= category.name %></a>
                  <% end %>
                </div>
              </div>
              
              <% if @current_user.present?%>
                <%= link_to "New Recipe", new_recipe_path, :class => 'nav_tab' %>
                <%= link_to "My Recipe",  users_index_path, :class => 'nav_tab' %>
        
              <% if @current_user.admin?%>
                <%= link_to "New Category", new_category_path, :class => 'nav_tab'  %>
                <%= link_to "All Categories", categories_path, :class => 'nav_tab' %>
              <% end %>

              <% if @current_user.present? %>
                <%= link_to "Log Out #{ @current_user.name }", login_path, :method => :delete, :class => 'nav_tab' %>
              <% end%>

              <% else %>
                <%= link_to "Sign Up", users_new_path, :class => 'nav_tab'%>
                <%= link_to "Sign In", login_path, :class => 'nav_tab' %>
              <% end %>
          </nav>
        </div>
      </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe, :html => { :multipart => true }) do |f| %>
    <%= f.label :title, 'Name' %>
    <%= f.text_field :title, :class => 'form_spacing', :size=>"50", :required => true, :placeholder => 'Butter Chicken' %><br>

    <%= f.label :servings %>
    <%= f.number_field :servings, :required => true, :placeholder => '2' %>

    <%= f.label :preptime, 'Prep Time' %>
    <%= f.text_field :preptime, :class => 'form_spacing', :size=>"24", :required => true, :placeholder => '1hr 5mins' %>

    <%= f.label :cooktime, 'Cooking Time' %>
    <%= f.text_field :cooktime, :size=>"24", :required => true, :placeholder => '1hr 5mins' %><br>

    <%= f.label :description %><br>
    <%= f.text_area :description, size: "110x2", :class => 'input_text form_spacing', :required => true, :placeholder => 'Aromatic golden chicken pieces in an incredible creamy curry sauce, this Butter Chicken recipe is one of the best you will try!'%><br>

    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients, :class => 'input_text form_spacing', size: "110x2.5",  :required => true, :placeholder => 'Comma(,) will separate into dot points. 4 eggs,1 scallion, 2 small to medium tomatoes, 3/4 tsp salt, 1/4 tsp white pepper, 1/2 tsp sesame oil, 1 tsp shaoxing wine, 3 tbsp vegetable oil, 2 tsp sugar, 1/4 - 1/2 cup water' %><br>

    <%= f.label :instructions %><br>
    <%= f.text_area :instructions, size: "110x5", :class => 'input_text form_spacing', :required => true, :placeholder => 'Underscore(_) will separate into numbered lists. 
    
In a bowl, combine chicken with all of the ingredients for the chicken marinade; let marinate for 30 minutes to an hour (or overnight if time allows)._

Heat oil in a large skillet or pot over medium-high heat._When sizzling, add chicken pieces in batches of two or three, making sure not to crowd the pan._

Fry until browned for only 3 minutes on each side. Set aside and keep warm._

You will finish cooking the chicken in the sauce._' %><br>
    <%# formatting above to suit textarea layout%>

    <%= f.label :image, 'Upload Image or attach link only' %>
    <%= f.url_field :image, :size=>"50", :class => 'form_spacing'%>
    <%= f.cl_image_upload :image %><br>
    
    <br>
    <%= f.label :video, 'Attach Video (YouTube or Vimeo)' %>
    <%= f.url_field :video, :class => 'form_spacing', :size=>"50", :placeholder => 'https://www.youtube.com/watch?v=Wn8ox93Qhus'%><br>

    <%= f.label :category_id, 'Select Category' %><br>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name  do |text| %>
        <%= text.label({ :class => 'checkbox_container' }) { text.check_box + text.text }%><br>
    <% end %>
    <br>
    
    <%# {} indicating not specifying additional options for check_boxes %>

    
    <%= f.submit class: 'submit_button' %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>

<div class="recipe_grid">
    <% @recipes.each do |recipe| %>
        <div class="show_image">
            <div class="index_thumbnail">
            <% if recipe.image.present?%>
                <%= link_to cl_image_tag(recipe.image), recipe %>
            <% else %>
                    <%= image_tag '/img/placeholder.png' %>
            <% end %>
            </div>
            <div class="index_content">
                <%= link_to recipe.title, recipe_path(recipe), :class => 'recipe_show_name' %>
            </div>
        </div>
    <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<h1 class="show_title"><%= @recipe.title %></h1>

<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category), :class => 'category_tag' %>
<% end %>

<br>
<h3> Servings: <span class="recipe_highlight"><%= @recipe.servings %></span><span class="separator"> &#160; | &#160;</span> </h3>
<h3> Prep Time: <span class="recipe_highlight"><%= @recipe.preptime %></span><span class="separator"> &#160; | &#160;</span> </h3>
<h3> Cooking Time: <span class="recipe_highlight"><%= @recipe.cooktime %><span></h3>

<div class="description_container">
    <p><%= @recipe.description %></p>
</div>

<% if @recipe.image.present?%>
    <%= cl_image_tag @recipe.image, :class => "recipe_image"%>
<% else %>
    <%= image_tag '/img/placeholder.png', :class => "recipe_image" %>
<% end%>
<%= get_video_iframe(@recipe.video) if @recipe.video.present? %>

<% ingredients_array = @recipe.ingredients.split(',') %>
<br>
<h3 class="recipe_heading">Ingredients</h3>
<ul class='dot_color'>
    <% ingredients_array.each do |ingredient| %>
        <li><%= ingredient.strip %></li>
    <% end %>
</ul>

<% instructions_array = @recipe.instructions.split('_') %>
<h3 class="recipe_heading">Instructions</h3>
<ol>
    <% instructions_array.each do |instruction| %>
        <li><%= instruction.strip %></li>
    <% end %>
</ol>

 <% if @can_edit %>
    <div class="control">
        <%= link_to "Edit Recipe", edit_recipe_path(@recipe), :class => "control_buttons" %>
        <%= link_to "Delete Recipe", @recipe, :method => :delete, :class => "control_buttons", :data => { :confirm => 'Are you sure?'} %>
    </div>
    
<% end %>

app/views/session/new.html.erb
<h1>Login</h1>


<%= form_tag login_path do %>
    <%= label_tag :email %><br>
    <%= email_field_tag :email, '', class: 'form_spacing', size:'50', placeholder: 'name@email.com' %><br>

    <%= label_tag :password %><br>
    <%= password_field_tag :password, '', class: 'form_spacing', size:'50'  %><br>

    <%= submit_tag "Sign in", class: 'submit_button' %>
<% end %>

<% if flash[:error].present?%>
    <ol>
        <li><%= flash[:error] %></h2>
    </ol>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>


<%= form_for @user do |f| %>
    <%= f.label :name %> <br>
    <%= f.text_field :name, :class => 'form_spacing', :size=>"35" %> <br>

    <%= f.label :email %><br>
    <%= f.email_field :email, :class => 'form_spacing', :size=>"35" %> <br>

    <%= f.label :password %><br>
    <%= f.password_field :password, :class => 'form_spacing', :size=>"35" %> <br>

    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, :class => 'form_spacing', :size=>"35" %> <br>

    <%= f.submit "Sign Up!", class: 'submit_button'  %>
<% end %>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end%>
    </ol>
<% end %>

app/views/users/show.html.erb
<h2> <%= @user.name %>'s Recipes </h2>  

<div class="recipe_grid">
<% if @current_user == @user %>
  <% @recipes.where(user_id: @current_user.id).each do |recipe| %>
    <div class="show_image">
      <div class="index_thumbnail">
          <%= link_to cl_image_tag(recipe.image), recipe %>
      </div>
      <div class="index_content">
        <%= link_to recipe.title, recipe_path(recipe), :class => 'recipe_show_name' %>
      </div>
    </div>
  <% end %>
<% end %>
</div>